const {make}=require('./harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');const results=[];
function test(name,fn){try{fn(make());results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}}
const eq=(g,s,v)=>assert.deepEqual(g.json(s),v),near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} vs ${b}`);
function arm(g){g.run('S.skills=["critsurge","soulrush","ghoststep"];paused=false;cur.hp=1e12;cur.atk=0;Math.random=()=>.999;buff.critsurge=skillNow()+5000;buff.soulrush=skillNow()+4000;player.invulnUntil=skillNow()+2000;renderCombat()');}
function advance(g,n){g.run(`for(let i=0;i<${Math.round(n*60)};i++)advanceCombat(1/60);renderCombat()`);}
for(const [name,state] of Object.entries({尸体:'cur.hp=1e18',已死敌人:'cur.hp=0',敌人入场:'enemyEntering=true',人物过场:'paused=true;transit=true',普通暂停:'paused=true',技能选择:'skillOfferOpen=true',确认:'confirmOpen=true',普通弹窗:'$("overlay").classList.add("show")',改装卡:'$("stageOverlay").hidden=false',受阻:'wall=true',死亡:'player.hp=0',后台:'document.hidden=true',重塑选择:'S.prestigeOffer={}',补给广告:'S.crateCooldownMs=0;openCrate()'}))test(name+'保留三技能时间与显示',g=>{arm(g);g.run(state);advance(g,6);eq(g,'skillNow()',0);eq(g,'activeSkillBuffs().filter(x=>x.ms!==null).map(x=>x.ms)',[5000,4000,2000]);assert(g.run('$("activeSkillBuffs").innerHTML').includes('暂停计时'));eq(g,'$("player").classList.contains("cloaked")',true);});
for(const rate of [1,2,4,8])test(`${rate}倍按实战消耗且各技能独立到期`,g=>{arm(g);g.run(`S.bestEver=100;testSpeed=${rate===2?1:rate};S.speed2=${rate===2}`);advance(g,1);eq(g,'skillNow()',rate*1000);eq(g,'activeSkillBuffs().filter(x=>x.ms!==null).map(x=>x.key)',rate===1?['critsurge','soulrush','ghoststep']:rate===2?['critsurge','soulrush']:rate===4?['critsurge']:[]);});
test('过场只冻结技能时钟，日志时钟和补给在线时钟仍推进',g=>{arm(g);g.run('paused=true;transit=true');advance(g,3);g.run('for(let i=0;i<30;i++)advanceCrateClock(.1)');eq(g,'[skillNow(),combatNow(),S.crateCooldownMs]',[0,3000,57000]);});
test('广告完成与取消后接着消耗剩余时间',g=>{for(const outcome of ['completed','cancelled']){g.run('S=freshState();beginPresentationRun();player={hp:100,shield:0};combatTick=skillTick=0;transit=false;wall=false');arm(g);advance(g,1);g.run('S.crateCooldownMs=0;openCrate()');advance(g,10);eq(g,'skillNow()',1000);g.run(`finishCrateAd(crateAd.id,'${outcome}')`);advance(g,1);eq(g,'skillNow()',2000);eq(g,'activeSkillBuffs().map(x=>x.key)',['critsurge','soulrush']);}});
test('暴击再次触发刷新5秒，不累加时长或层数，打盾也触发',g=>{arm(g);g.run('S.skills=["critsurge","critsurge","critsurge"];cur.shield=1e12;Math.random=()=>0;skillTick=180;dealPlayerHit()');eq(g,'buff.critsurge-skillNow()',5000);near(g.run('calcStats().aspd'),1.3*1.9);g.run('dealPlayerHit()');eq(g,'buff.critsurge-skillNow()',5000);assert(g.run('$("activeSkillBuffs").innerHTML').includes('攻速 +90%'));});
test('破盾触发4秒，再次破盾刷新不叠时长',g=>{arm(g);g.run('S.skills=["soulrush","soulrush"];cur.shield=1;dealPlayerHit()');eq(g,'buff.soulrush-skillNow()',4000);near(g.run('calcStats().aspd'),1.3*1.5);advance(g,1);g.run('cur.shield=1;dealPlayerHit()');eq(g,'buff.soulrush-skillNow()',4000);});
test('暴击破盾同时击杀，三增益立即显示并保留到新怪战斗',g=>{arm(g);g.run('cur.hp=1;cur.shield=1;Math.random=()=>0;dealPlayerHit()');eq(g,'cur.hp',1e18);eq(g,'activeSkillBuffs().map(x=>x.key)',['critsurge','soulrush','ghoststep']);advance(g,5);eq(g,'skillNow()',0);eq(g,'player.pendingInvuln',2000);});
for(let stage=1;stage<=5;stage++)for(const mode of ['endless','build'])test(`${mode}阶段${stage}真实换怪期间不扣无敌/攻速，开战才扣`,g=>{arm(g);g.run(`gameMode='${mode}';S.mode='${mode}';S.stage=${stage};S.skills=['critsurge','soulrush','ghoststep','ghoststep'];spawnMob();mobKind='trooper';onKill()`);g.advance(1900);advance(g,1);eq(g,'skillNow()',0);eq(g,'player.pendingInvuln',2500);eq(g,'enemyEntering',true);g.advance(300);g.run("cur.hp=1e12;cur.atk=0");advance(g,1);eq(g,'skillNow()',1000);eq(g,'player.invulnUntil-skillNow()',1500);eq(g,'buff.critsurge-skillNow()',4000);});
test('新敌人已生成但仍暂停等待时不扣时',g=>{arm(g);g.run('paused=true;player.pendingInvuln=2000;spawnMob()');advance(g,5);eq(g,'skillNow()',0);g.run('paused=false');advance(g,1);eq(g,'player.invulnUntil-skillNow()',1000);});
test('无敌期间仍扣技能时间，到期重新承伤',g=>{arm(g);g.run('player.shield=0;cur.atk=10');advance(g,1);eq(g,'player.hp',100);advance(g,2);assert(g.run('player.hp')<100);eq(g,'$("player").classList.contains("cloaked")',false);});
test('无敌待生效只显示，不提前授予免伤',g=>{arm(g);g.run('player.invulnUntil=0;player.pendingInvuln=2000;cur.atk=10;player.shield=0');advance(g,1);near(g.run('player.hp'),90);});
test('Boss蓄力、攻击间隔均按战斗扣时',g=>{arm(g);g.run('S.stage=5;S.floor=100;S.mobIdx=5;spawnMob();cur.hp=1e12;cur.atk=0;cur.phase=1;cur.phaseT=.5');advance(g,1);eq(g,'skillNow()',1000);});
test('条件技能按生命阈值显示，不添加倒计时',g=>{arm(g);g.run('S.skills=["adrenaline","lowhp"];player.hp=20;renderCombat()');eq(g,'activeSkillBuffs().map(x=>[x.key,x.ms])',[['adrenaline',null],['lowhp',null]]);g.run('player.hp=40;renderCombat()');eq(g,'activeSkillBuffs().map(x=>x.key)',['adrenaline']);g.run('player.hp=50;renderCombat()');eq(g,'activeSkillBuffs()',[]);eq(g,'$("activeSkillBuffs").hidden',true);});
test('到期仅删除激活状态，仍显示已获得技能说明',g=>{arm(g);advance(g,6);g.run('renderPanels()');eq(g,'$("activeSkillBuffs").hidden',true);assert(g.run('$("skillBox").innerHTML').includes('狂暴节奏'));});
test('重塑及复位清理激活状态',g=>{arm(g);g.run('wall=true;doPrestige();applyPrestige(1);renderCombat()');eq(g,'activeSkillBuffs()',[]);arm(g);g.run('doReset();renderCombat()');eq(g,'activeSkillBuffs()',[]);});
test('晋升清理旧增益并保留新阶段基础盾',g=>{arm(g);g.run('S.floor=100;S.mobIdx=5;spawnMob();onKill();showStageUpgrade();commitStageUpgrade();stageClock.elapsed=8;completeStageAnimation();enterNextStage();renderCombat()');eq(g,'activeSkillBuffs()',[]);eq(g,'player.shield',15);});
test('文案精简保持技能机制和面板真实总护盾',g=>{g.run('S.stage=3;S.skills=["shield","shield"];spawnMob();renderPanels()');eq(g,'[SKILLS.shield.d,SKILLS.overclock.d]',['获得10%最大生命护盾','暴击率 +10%']);near(g.run('calcStats().shieldPct'),.4);const s=g.run('$("skillBox").innerHTML');assert(s.includes('Lv.4')&&s.includes('40%')&&!s.includes('阶段自带'));});
fs.writeFileSync(__dirname+'/timed-results.json',JSON.stringify(results,null,2));console.log(`${results.filter(r=>r.status==='PASS').length}/${results.length} PASS`);for(const r of results.filter(r=>r.status==='FAIL'))console.log(r.name,r.error);if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
