const {make}=require('./harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');const results=[];
function test(name,fn){try{fn(make());results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}}
const eq=(g,s,v)=>assert.deepEqual(g.json(s),v);
test('技能目录14项、触发池5项、无残留技能定义',g=>{eq(g,'[Object.keys(SKILLS).length,POOL_5.length,POOL_10.length,Boolean(SKILLS.killcycle),TRIGGER_KEYS.has("killcycle"),Boolean(SKILL_TOTAL.killcycle)]',[14,5,9,false,false,false]);});
for(let stage=1;stage<=5;stage++)test(`阶段${stage}旧档清理重复已获技能、保留其余成长与刷新幂等`,g=>{const d=g.json(`({...S,stage:${stage},gold:321,souls:45,runSouls:7,atkLv:12,hpLv:9,skills:['fire','killcycle','ghoststep','killcycle','critsurge'],tree:{dmg:2,gold:3,soul:1},crateCooldownMs:12345})`);g.storage.set('neonHunter',JSON.stringify(d));g.run('load();spawnMob();renderPanels()');eq(g,'[S.stage,S.gold,S.souls,S.runSouls,S.atkLv,S.hpLv,S.skills,S.tree,S.crateCooldownMs]',[stage,321,45,7,12,9,['fire','ghoststep','critsurge'],{dmg:2,gold:3,soul:1},12345]);assert(!g.run('$("skillBox").innerHTML').includes('杀戮循环'));g.run('save();load()');eq(g,'S.skills',['fire','ghoststep','critsurge']);});
test('旧待选恢复：保留有效两项并补足第三项、写存档',g=>{const d=g.json(`({...S,pendingOffer:{pool:'p5',picks:['killcycle','ghoststep','soulrush'],floor:15}})`);g.storage.set('neonHunter',JSON.stringify(d));g.run('load();offerSkills(S.pendingOffer.pool,S.pendingOffer.picks,S.pendingOffer.floor)');const p=g.json('curOffer');assert.equal(p.length,3);assert.equal(new Set(p).size,3);assert(p.includes('ghoststep')&&p.includes('soulrush')&&!p.includes('killcycle'));eq(g,'S.pendingOffer.floor',15);assert(!JSON.parse(g.storage.get('neonHunter')).pendingOffer.picks.includes('killcycle'));});
test('已删除选项旧回调不授予技能、不关闭有效选择',g=>{g.run('offerSkills("p5",["ghoststep","soulrush","critsurge"],5);pickSkill("killcycle")');eq(g,'[S.skills,skillOfferOpen]',[[],true]);g.run('pickSkill("ghoststep")');eq(g,'[S.skills,skillOfferOpen,S.pendingOffer]',[['ghoststep'],false,null]);});
test('确认框延迟恢复旧待选也过滤并补齐',g=>{g.run('confirmOpen=true;offerSkills("p5",["killcycle","ghoststep","soulrush"],25);confirmOpen=false;offerSkills(pendingSkillOffer.pool,pendingSkillOffer.picks,pendingSkillOffer.floor)');assert(!g.json('curOffer').includes('killcycle'));eq(g,'[curOffer.length,S.pendingOffer.floor]',[3,25]);});
test('随机1000次三选一均唯一有效且覆盖剩余5技能',g=>{const seen=new Set();for(let i=0;i<1000;i++){g.run('offerSkills("p5",null,5)');const p=g.json('curOffer');assert.equal(p.length,3);assert.equal(new Set(p).size,3);assert(!p.includes('killcycle'));p.forEach(x=>seen.add(x));}assert.equal(seen.size,5);});
test('异常全旧技能待选仍能补足有效三项',g=>{g.run('offerSkills("p5",["killcycle","killcycle","killcycle"],5)');assert.equal(new Set(g.json('curOffer')).size,3);assert(!g.json('curOffer').includes('killcycle'));});
test('无杀戮循环触发或攻速残留，狂暴节奏仍正常',g=>{g.run('S.skills=["killcycle","critsurge"];Math.random=()=>0;cur.hp=1e12;dealPlayerHit()');assert(Math.abs(g.run('calcStats().aspd')-1.3*1.3)<1e-9);eq(g,'Object.hasOwn(buff,"killcycle")',false);g.run('combatTick=301');assert.equal(g.run('calcStats().aspd'),1.3);});
test('无剩余触发技能的旧档读后面板可正常显示',g=>{const d=g.json(`({...S,skills:['killcycle']})`);g.storage.set('neonHunter',JSON.stringify(d));g.run('load();renderPanels()');eq(g,'S.skills',[]);assert.equal(g.run('$("skillBox").innerHTML'),'尚未获得');});
test('重塑与升阶重置增益不再创建旧状态',g=>{g.run('wall=true;doPrestige();applyPrestige(1)');eq(g,'Object.hasOwn(buff,"killcycle")',false);g.run('S.floor=100;S.mobIdx=5;spawnMob();onKill();commitStageUpgrade()');eq(g,'Object.hasOwn(buff,"killcycle")',false);});
fs.writeFileSync(__dirname+'/removal-results.json',JSON.stringify(results,null,2));console.log(`${results.filter(x=>x.status==='PASS').length}/${results.length} PASS`);for(const r of results.filter(x=>x.status==='FAIL'))console.log(r);if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
