const {make}=require('./harness.cjs'),assert=require('assert'),fs=require('fs');const results=[];const snapshots=[];
function test(name,fn){try{const g=make();const evidence=fn(g);results.push({name,status:'PASS',evidence});}catch(e){results.push({name,status:'FAIL',error:e.stack});}}
const eq=(g,s,v)=>assert.deepStrictEqual(g.json(s),v);
function setup(g,rate,aspd=10){g.run(`testSpeed=${rate===2?1:rate};S.speed2=${rate===2};S.bestEver=200;S.stage=5;S.floor=100;S.mobIdx=5;spawnMob();paused=false;cur.hp=cur.max=1e14;cur.atk=1;cur.shield=0;cur.maxShield=1e14;player.hp=1e9;var hits=0,rawHit=dealPlayerHit;const rawStats=calcStats;calcStats=()=>({...rawStats(),aspd:${aspd},hp:1e9,crit:0});dealPlayerHit=()=>{hits++;rawHit()};renderCombat=renderPanels=()=>{};`);}
function frames(g,fps,seconds){g.run(`for(let i=0;i<${Math.round(fps*seconds)};i++){__advance(${1000/fps});loop(performance.now());}`);}
for(const fps of [15,30,60])for(const rate of [1,2,4,8])test(`${fps}fps ${rate}× 攻击/主炮/伤害同24游戏秒`,g=>{setup(g,rate);frames(g,fps,24/rate);const a=g.json('({hits,t:combatNow(),enemyHp:cur.hp,hp:player.hp,phase:cur.phase,phaseT:cur.phaseT,wall})');assert.equal(a.hits,240);assert.equal(a.t,24000);assert.equal(a.wall,false);if(snapshots.length)assert.deepStrictEqual(a,snapshots[0]);snapshots.push(a);return a;});
for(const rate of [1,4,8])test(`${rate}× 300次/秒超帧攻速完整结算`,g=>{setup(g,rate,300);frames(g,30,4/rate);eq(g,'hits',1200);});
for(const rate of [1,4,8])test(`${rate}× 迷彩按2游戏秒结束`,g=>{setup(g,rate,0);g.run('player.invulnUntil=combatNow()+2000');frames(g,120,1/rate);eq(g,'player.hp',1e9);frames(g,120,2/rate);assert(g.run('player.hp<1e9'));eq(g,'combatNow()',3000);});
test('1/4/8按钮循环、新层可用、与普通2×不叠乘',g=>{g.run('S.speed2=true;S.bestEver=100;S.prestiges=1;toggleTestSpeed()');eq(g,'[testSpeed,effSpeed(),S.speed2]',[4,4,false]);g.run('S.floor=200;toggleTestSpeed()');eq(g,'effSpeed()',8);g.run('toggleTestSpeed()');eq(g,'effSpeed()',1);g.run('toggleTestSpeed();S.floor=1;toggleSpeed()');eq(g,'[testSpeed,effSpeed()]',[1,2]);});
test('测试倍率不写入玩家存档，普通2×偏好关闭',g=>{g.run('toggleTestSpeed();toggleTestSpeed();save()');const d=JSON.parse(g.storage.get('neonHunter'));assert.equal(d.speed2,false);assert(!('testSpeed' in d));const reload=make();reload.storage.set('neonHunter',g.storage.get('neonHunter'));reload.run('load()');eq(reload,'[testSpeed,effSpeed()]',[1,1]);});
test('中途切速保留攻击进度和Boss相位',g=>{setup(g,1);g.run('atkTimer=.6;cur.phaseT=3.125;toggleTestSpeed()');eq(g,'[atkTimer,cur.phaseT]',[.6,3.125]);g.run('toggleTestSpeed();toggleTestSpeed()');eq(g,'[atkTimer,cur.phaseT]',[.6,3.125]);});
test('提示弹窗暂停时不消耗增益或积累追帧',g=>{setup(g,8);g.run('buff.killcycle=3000;paused=true;skillOfferOpen=true');frames(g,30,2);eq(g,'[combatNow(),hits,combatRemainder]',[0,0,0]);g.run('skillOfferOpen=false;paused=false');frames(g,60,.25);eq(g,'[combatNow(),hits]',[2000,20]);});
test('后台战斗/过场都冻结，回来不补跑',g=>{setup(g,8);g.run('var calls=0;afterPresentation(800,()=>calls++);document.hidden=true;setPresentationHidden(true)');frames(g,30,10);eq(g,'[combatNow(),hits,calls]',[0,0,0]);g.run('document.hidden=false;setPresentationHidden(false)');g.advance(99);eq(g,'calls',0);g.advance(2);eq(g,'calls',1);});
test('后台创建的计时任务到前台才计时',g=>{g.run('document.hidden=true;setPresentationHidden(true);var calls=0;afterPresentation(800,()=>calls++);testSpeed=8;syncPresentationSpeed()');g.advance(10000);eq(g,'calls',0);g.run('document.hidden=false;setPresentationHidden(false)');g.advance(101);eq(g,'calls',1);});
test('后台返回一帧不会结算隐藏时间',g=>{setup(g,8);frames(g,60,.25);g.run('document.hidden=true;setPresentationHidden(true)');g.advance(100000);g.run('document.hidden=false;setPresentationHidden(false);loop(performance.now())');eq(g,'combatNow()',2000);});
test('自动保存仍是现实5秒一次',g=>{setup(g,8);g.run('var writes=0;save=()=>writes++');frames(g,60,15);assert(g.run('writes>=2&&writes<=3'));return g.run('writes');});
test('单步击杀不会重复发掉落或攻击下一只',g=>{setup(g,8,300);g.run('S.floor=1;S.mobIdx=0;cur.hp=1;cur.shield=0;var kills=0,realKill=onKill;onKill=()=>{kills++;realKill()};advanceCombat(.1)');eq(g,'[hits,kills,S.mobIdx]',[1,1,1]);});
test('单步死亡立即停剩余攻击/伤害',g=>{setup(g,8,0);g.run('player.hp=.001;cur.atk=100;advanceCombat(.1)');eq(g,'[wall,paused]',[true,true]);assert(g.run('combatNow()<=17'));});
test('极短Boss相位跨越余量保持',g=>{setup(g,1,0);g.run('cur.phase=0;cur.phaseT=.001;combatStep(.016)');eq(g,'cur.phase',1);assert(Math.abs(g.run('cur.phaseT')-.485)<1e-10);});
for(const n of [1,2,3,4])test(`8×阶段${n}百层只结算一次，完整演出独立`,g=>{g.run(`testSpeed=8;S.stage=${n};S.floor=100;S.mobIdx=5;spawnMob();onKill();onKill()`);g.advance(176);eq(g,'[S.stage,S.stageUpgrade.status,S.stageHistory.length]',[n,'clear',0]);g.run('commitStageUpgrade();advanceCombat(.1);enterNextStage();completeStageAnimation()');eq(g,'[S.stage,S.stageUpgrade.status,stageClock.elapsed]',[n+1,'playing',0]);});
test('无尽100/200层可继续，不升第六阶段',g=>{for(const f of [100,200]){g.run(`S=freshState();S.stage=5;testSpeed=8;S.floor=${f};S.mobIdx=5;spawnMob();onKill()`);g.advance(176);eq(g,'[S.stageUpgrade,S.prestigeOffer.floor,S.floor]',[null,f,f+1]);g.run('continueMilestone();pickSkill(curOffer[0])');g.advance(1200);eq(g,'[S.stage,paused]',[5,false]);}});
test('8×广告重塑、重复回调只结算一次',g=>{g.run('testSpeed=8;S.stage=5;S.runSouls=10;wall=true;doPrestige();requestPrestigeAd();var ad=prestigeAd.attempt;finishPrestigeAd(ad,"completed");finishPrestigeAd(ad,"completed")');eq(g,'[S.stage,S.souls,S.floor,S.prestiges,testSpeed]',[5,20,1,1,8]);});
test('途中换速按剩余动画时间调度，不重复回调',g=>{g.run('var calls=0;afterPresentation(1000,()=>calls++)');g.advance(400);g.run('toggleTestSpeed()');g.advance(149);eq(g,'calls',0);g.advance(2);eq(g,'calls',1);g.advance(1000);eq(g,'calls',1);});
test('复位后旧的高速过场回调作废',g=>{g.run('testSpeed=8;S.floor=10;S.mobIdx=5;spawnMob();onKill();doReset()');g.advance(3000);eq(g,'[S.floor,S.prestigeOffer,S.pendingOffer||null]',[1,null,null]);});
test('测试日志标记倍率、现实时间和游戏时间',g=>{setup(g,1);g.run('toggleTestSpeed()');frames(g,60,.5);g.run('logEvent("probe");pushFloorSummary()');const e=g.json('curSession.events.at(-1)');assert.equal(e.rate,4);assert.equal(e.testRate,4);assert.equal(e.gameT,2000);assert(Math.abs(e.t-500)<1e-5);assert(g.run('curSession.testSpeedUsed'));assert(g.run('csvContent(curSession).includes("game_clear_dur_s")'));});
test('暂停中技能计时冻结且恢复后按倍率到期',g=>{setup(g,8,0);g.run('S.skills=["killcycle"];buff.killcycle=combatNow()+3000;paused=true');frames(g,60,2);assert(g.run('buff.killcycle>combatNow()'));g.run('paused=false');frames(g,120,.25);assert(g.run('buff.killcycle>combatNow()'));frames(g,120,.125);assert(g.run('buff.killcycle<=combatNow()'));});
test('现实卡顿最多推进100ms，不追跑积压秒数',g=>{setup(g,8);g.advance(10000);g.run('loop(performance.now())');eq(g,'[combatNow(),hits]',[800,8]);});
test('日志刷新后游戏时间延续，无负数倒退',g=>{setup(g,8);frames(g,120,.25);g.run('saveLogs(true);combatTick=0;curSession=null;loadLogs();logEvent("restored")');eq(g,'curSession.events.at(-1).gameT',2000);});
fs.writeFileSync(__dirname+'/speed-results.json',JSON.stringify(results,null,2));console.log(`${results.filter(r=>r.status==='PASS').length}/${results.length} PASS`);for(const r of results.filter(r=>r.status==='FAIL'))console.log(r.name,r.error);if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
