const assert=require('assert'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {make}=require('./harness.cjs');const results=[];
function test(name,fn){try{const g=make();g.run('$("stageOverlay").hidden=true');fn(g);results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function select(g,mode){g.run('boot.phase="cover"');return g.run(`selectMode('${mode}')`)}
function state(g,key='neonHunter'){return JSON.parse(g.storage.get(key));}
function unlock(g){g.run('S.stage=5;save()');}
function build(g){unlock(g);g.run('gameMode="build";load();newSession();spawnMob()');}
const stamp=g=>g.run('S.gold=1234;S.souls=19;S.runSouls=7;S.tree.dmg=3;S.skills=["ghoststep"];S.atkLv=4;S.hpLv=5;S.crateCooldownMs=12345;save()');
test('全新用户仅无尽，构筑禁止选择',g=>{assert.equal(g.run('gameMode'),'endless');assert.equal(select(g,'build'),false);assert.equal(g.run('window.reloads'),0);});
test('无尽1–4阶段未解锁',g=>{for(let stage=1;stage<=4;stage++){g.run(`S.stage=${stage};save()`);assert.equal(g.run('buildUnlocked()'),false);}});
test('阶段四完成提交才解锁',g=>{g.run('S.stage=4;S.floor=100;S.stageUpgrade={id:"u",from:4,to:5,status:"clear",elapsed:0};save()');assert.equal(g.run('buildUnlocked()'),false);assert(g.run('commitStageUpgrade()'));assert.equal(state(g).stage,5);assert(g.run('buildUnlocked()'));assert.equal(state(g,'neonHunterModes').buildUnlocked,true);});
test('升阶写入失败不解锁、不清资源',g=>{g.run('S.stage=4;S.gold=100;S.stageUpgrade={id:"u",from:4,to:5,status:"clear",elapsed:0};save();localStorage.setItem=()=>{throw Error("full")}');assert.equal(g.run('commitStageUpgrade()'),false);assert.equal(g.run('S.gold'),100);assert.equal(g.run('buildUnlocked()'),false);});
test('已达阶段五旧档自动解锁且完整保留',g=>{stamp(g);const old=state(g);old.stage=5;delete old.mode;g.storage.set('neonHunter',JSON.stringify(old));assert(g.run('load()'));assert.equal(g.run('S.gold'),1234);assert(g.run('buildUnlocked()'));assert.equal(state(g,'neonHunterModes').buildUnlocked,true);});
test('解锁标记写入失败仍有已提交存档凭据',g=>{g.run('const realSet=localStorage.setItem;localStorage.setItem=(k,v)=>{if(k==="neonHunterModes")throw Error("full");realSet(k,v)};S.stage=5;save()');assert(g.run('buildUnlocked()'));assert.equal(select(g,'build'),false);assert.equal(g.run('window.reloads'),0);});
test('第五星构筑档自身不能解锁',g=>{g.run('gameMode="build";S=freshState();S.stage=5;save()');assert.equal(g.run('buildUnlocked()'),false);});
test('模式切换写选择后刷新，当前页存档键不变',g=>{unlock(g);stamp(g);assert(select(g,'build'));assert.equal(state(g,'neonHunterModes').selected,'build');assert.equal(g.run('gameMode'),'endless');g.run('save()');assert.equal(state(g).gold,1234);assert(!g.storage.has('neonHunter.build'));assert.equal(g.run('window.reloads'),1);});
test('真实初始化按共享配置选中构筑，初始资源清零',g=>{unlock(g);stamp(g);assert(select(g,'build'));const h=make(4,g.storage);assert.equal(h.run('gameMode'),'build');assert.equal(h.run('load()'),false);assert.deepEqual(h.json('[S.stage,S.floor,S.gold,S.souls,S.skills.length]'),[1,1,0,0,0]);});
test('两模式资源技能树冷却存档互相独立',g=>{unlock(g);stamp(g);const endless=g.storage.get('neonHunter');g.run('gameMode="build";load();S.gold=80;S.skills=["fire"];S.crateCooldownMs=900;save()');assert.equal(g.storage.get('neonHunter'),endless);assert.equal(state(g,'neonHunter.build').gold,80);g.run('gameMode="endless";load()');assert.deepEqual(g.json('[S.gold,S.souls,S.tree.dmg,S.skills,S.crateCooldownMs]'),[1234,19,3,['ghoststep'],12345]);});
test('双标签页选择改变不改另一页存档键',g=>{unlock(g);stamp(g);select(g,'build');const h=make(5,g.storage);h.run('load();S.gold=77;save()');g.run('S.gold=1235;save()');assert.equal(state(g).gold,1235);assert.equal(state(g,'neonHunter.build').gold,77);});
test('元配置未知版本不覆盖，安全进入无尽',g=>{g.storage.set('neonHunterModes','{"schema":99,"selected":"build","buildUnlocked":true}');const h=make(3,g.storage);assert.equal(h.run('gameMode'),'endless');assert.equal(h.run('writeModePrefs("endless")'),false);assert.equal(state(g,'neonHunterModes').schema,99);});
test('无解锁的伪选择不能加载构筑',g=>{g.storage.set('neonHunterModes',JSON.stringify({schema:1,selected:'build',buildUnlocked:false}));assert.equal(make(3,g.storage).run('gameMode'),'endless');});
test('旧无阶段档备份迁移保留资源',g=>{stamp(g);const d=state(g);delete d.stageSchema;delete d.economySchema;delete d.mode;g.storage.set('neonHunter',JSON.stringify(d));g.run('load()');assert.equal(g.run('S.gold'),1234);assert(g.storage.has('neonHunter.preStages'));assert(g.storage.has('neonHunter.preEconomy'));});
test('迁移备份按模式隔离',g=>{build(g);stamp(g);const d=state(g,'neonHunter.build');delete d.stageSchema;delete d.economySchema;g.storage.set('neonHunter.build',JSON.stringify(d));g.run('load()');assert(g.storage.has('neonHunter.build.preStages'));assert(g.storage.has('neonHunter.build.preEconomy'));assert(!g.storage.has('neonHunter.preStages'));});
test('模式标记不匹配阻止覆盖',g=>{const d=g.json('freshState()');d.mode='build';g.storage.set('neonHunter',JSON.stringify(d));assert.equal(g.run('load()'),false);assert(g.run('saveBlocked'));assert.equal(g.run('save()'),false);assert.equal(state(g).mode,'build');});
test('损坏当前档不写坏，可切换另一个可用档',g=>{unlock(g);g.storage.set('neonHunter','broken');g.run('load()');assert(g.run('saveBlocked'));assert(select(g,'build'));assert.equal(g.storage.get('neonHunter'),'broken');});
test('存档写失败阻止切换',g=>{unlock(g);g.run('localStorage.setItem=()=>{throw Error("full")}');assert.equal(select(g,'build'),false);assert.equal(g.run('window.reloads'),0);});
test('加载中和弹窗期间不可切模式',g=>{unlock(g);g.run('boot.phase="loading"');assert.equal(g.run('selectMode("build")'),false);g.run('boot.phase="cover";$("overlay").classList.add("show")');assert.equal(g.run('selectMode("build")'),false);});
test('返回封面保存当前模式并刷新',g=>{stamp(g);assert(g.run('returnToCover()'));assert.equal(state(g).gold,1234);assert.equal(g.run('window.reloads'),1);});
test('强制改装演出中不可返回封面',g=>{g.run('S.stageUpgrade={status:"playing"}');assert.equal(g.run('returnToCover()'),false);});
test('构筑每个5层/10层节点都列全部14技能',g=>{build(g);for(const p of ['p5','p10']){g.run(`offerSkills('${p}',null,10)`);assert.equal(g.run('curOffer.length'),14);assert.deepEqual(g.json('curOffer'),g.json('Object.keys(SKILLS)'));assert.equal(state(g,'neonHunter.build').pendingOffer.picks.length,14);}});
test('构筑不消费随机技能抽取，包含两池',g=>{build(g);g.run('Math.random=()=>{throw Error("random should not run")};offerSkills("p5",null,5)');assert.equal(g.run('curOffer.length'),14);});
test('构筑选择任一项只增加一次',g=>{build(g);g.run('offerSkills("p5",null,5);pickSkill("fire");pickSkill("neuro")');assert.deepEqual(g.json('S.skills'),['fire']);assert.equal(g.run('S.pendingOffer'),null);});
test('构筑非法技能名不会被获得',g=>{build(g);g.run('offerSkills("p5",null,5);pickSkill("killcycle")');assert.deepEqual(g.json('S.skills'),[]);assert(g.run('skillOfferOpen'));});
test('构筑刷新恢复待选仍展示全部技能',g=>{build(g);g.run('offerSkills("p5",["ghoststep","killcycle"],5);load();offerSkills(S.pendingOffer.pool,S.pendingOffer.picks,S.pendingOffer.floor)');assert.equal(g.run('curOffer.length'),14);assert(!g.run('curOffer.includes("killcycle")'));});
test('重复光学迷彩文案为增加0.5秒',g=>{build(g);g.run('S.skills=["ghoststep"];offerSkills("p10",null,10)');assert(g.nodes.get('modalBox').innerHTML.includes('无敌持续时间增加 0.5 秒'));});
test('无尽两池保持随机不重复三选一',g=>{for(const p of ['p5','p10']){g.run(`offerSkills('${p}',null,10)`);assert.equal(g.run('curOffer.length'),3);assert.equal(g.run('new Set(curOffer).size'),3);assert(g.run(`curOffer.every(k=>${p==='p5'?'POOL_5':'POOL_10'}.includes(k))`));}});
test('旧待选过滤删除技能并去重补足三个',g=>{g.run('offerSkills("p5",["ghoststep","ghoststep","killcycle"],5)');assert.equal(g.run('new Set(curOffer).size'),3);assert(g.run('curOffer.includes("ghoststep")'));});
test('构筑重塑只清构筑技能，另一档保持',g=>{build(g);const old=g.storage.get('neonHunter');g.run('S.skills=["fire"];S.runSouls=8;S.floor=10;S.prestigeOffer=makePrestigeOffer("milestone",10,"preview")');g.run('applyPrestige(1)');assert.equal(g.storage.get('neonHunter'),old);assert.equal(state(g,'neonHunter.build').souls,8);assert.equal(state(g,'neonHunter.build').skills.length,0);});
test('构筑升阶写入构筑键，8秒流程仍在',g=>{build(g);const old=g.storage.get('neonHunter');g.run('S.stageUpgrade={id:"build-u",from:1,to:2,status:"clear",elapsed:0}');assert(g.run('commitStageUpgrade()'));assert.equal(state(g,'neonHunter.build').stage,2);assert.equal(state(g,'neonHunter.build').stageUpgrade.status,'playing');assert.equal(g.storage.get('neonHunter'),old);assert.equal(g.run('completeStageAnimation()'),false);});
test('构筑复位不清无尽进度及解锁',g=>{build(g);stamp(g);const old=g.storage.get('neonHunter');assert(g.run('doReset()'));assert.equal(state(g,'neonHunter.build').gold,0);assert.equal(g.storage.get('neonHunter'),old);assert(g.run('buildUnlocked()'));});
test('无尽复位不清构筑且永久保留解锁',g=>{build(g);stamp(g);const old=g.storage.get('neonHunter.build');g.run('gameMode="endless";load()');assert(g.run('doReset()'));assert.equal(state(g).stage,1);assert.equal(g.storage.get('neonHunter.build'),old);assert(g.run('buildUnlocked()'));});
test('复位写失败，内存/原始存档未清空',g=>{stamp(g);const old=g.storage.get('neonHunter');g.run('localStorage.setItem=()=>{throw Error("full")}');assert.equal(g.run('doReset()'),false);assert.equal(g.run('S.gold'),1234);assert.equal(g.storage.get('neonHunter'),old);});
test('未持久化解锁前不允许清除阶段五凭据',g=>{g.run('S.stage=5;save()');g.storage.delete('neonHunterModes');g.run('const set=localStorage.setItem;localStorage.setItem=(k,v)=>{if(k==="neonHunterModes")throw Error("full");set(k,v)}');assert.equal(g.run('doReset()'),false);assert.equal(state(g).stage,5);});
test('日志键与导出文件名包含模式，防覆盖',g=>{g.run('saveLogs(true)');const old=g.storage.get('neonHunterLogs');build(g);g.run('saveLogs(true)');assert(g.storage.has('neonHunterLogs.build'));assert.equal(g.storage.get('neonHunterLogs'),old);assert(g.run('sessionBaseName(curSession)').includes('_build_'));assert.equal(state(g,'neonHunterLogs.build').current.mode,'build');});
test('构筑补给原子结算不覆盖无尽',g=>{build(g);const old=g.storage.get('neonHunter');g.run('S.crateCooldownMs=0;openCrate();finishCrateAd(crateAd.id,"completed")');assert.equal(g.storage.get('neonHunter'),old);assert.equal(state(g,'neonHunter.build').cratesRun,1);});
const html=fs.readFileSync(process.env.GAME_HTML,'utf8');
const report={version:'v2.57',hash:crypto.createHash('sha256').update(html).digest('hex'),count:results.length,passed:results.filter(x=>x.pass).length,results};fs.writeFileSync(path.join(__dirname,'modes-results.json'),JSON.stringify(report,null,2));console.log(`${report.passed}/${report.count} PASS`);results.filter(x=>!x.pass).forEach(x=>console.log(x.name,x.error));if(report.passed!==report.count)process.exitCode=1;
