const assert=require('assert'),{make}=require('./harness.cjs');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
for(const profile of ['development','basic']){
 const fresh=()=>make(29,new Map(),profile);
 test(profile+' keeps normal upgrades and player 2x',()=>{const g=fresh();g.run('S.gold=6;$("btnAtk").onclick();S.prestiges=1;S.bestEver=10;S.floor=2;toggleSpeed()');assert.equal(g.run('S.atkLv'),1);assert.equal(g.run('effSpeed()'),2);g.run('S.floor=11');assert.equal(g.run('effSpeed()'),1);});
 test(profile+' preserves independent mode saves',()=>{const g=fresh();g.run('S.gold=31;save();gameMode="build";S=freshState();S.gold=52;save();gameMode="endless";load()');assert.equal(g.run('S.gold'),31);assert.equal(JSON.parse(g.storage.get('neonHunter.build')).gold,52);});
 test(profile+' keeps ordinary reforge',()=>{const g=fresh();g.run('S.runSouls=7;wall=true;doPrestige();applyPrestige(1)');assert.equal(g.run('S.souls'),7);assert.equal(g.run('S.prestiges'),1);});
}
test('Basic cannot collect/clear/export logs or reset through hidden handlers',()=>{const g=make(29,new Map(),'basic');g.run('S.gold=77;save();askReset();doReset();askCoverReset();endTest();toggleDrawer();exportJSON("S01");exportCSV("S01");saveLogs(true);newSession();logEvent("test");pushFloorSummary();toggleTestSpeed()');assert.equal(g.run('S.gold'),77);assert.equal(g.run('testSpeed'),1);assert.equal(g.run('curSession'),null);assert(!g.nodes.get('overlay')?.classList.contains('show'));assert(![...g.storage.keys()].some(k=>k.startsWith('neonHunterLogs')));});
test('Development retains tools and simulated ads',()=>{const g=make();g.run('toggleTestSpeed();S.crateCooldownMs=0;openCrate()');assert.equal(g.run('testSpeed'),4);assert(g.run('Boolean(curSession&&crateAd)'));assert(g.run('$("modalBox").innerHTML.includes("模拟完整观看")'));});
test('Basic free supply pays once, persists reward and cooldown together, and does not pause',()=>{const g=make(29,new Map(),'basic');g.run('S.crateCooldownMs=0;paused=false');const gold=g.run('Math.round(mobGold(S.floor)*CRATE_GOLD_MULT*calcStats().goldMult)');g.run('openCrate();openCrate()');assert.equal(g.run('S.gold'),gold);assert.equal(g.run('S.cratesRun'),1);assert.equal(g.run('S.crateCooldownMs'),60000);assert.equal(g.run('paused'),false);assert.equal(g.run('crateAd'),null);assert.equal(JSON.parse(g.storage.get('neonHunter')).gold,gold);});
test('Basic free supply storage failure retains reward opportunity',()=>{const g=make(29,new Map(),'basic');g.run('S.crateCooldownMs=0;localStorage.setItem=()=>{throw Error("quota")};openCrate()');assert.equal(g.run('S.gold'),0);assert.equal(g.run('S.crateCooldownMs'),0);assert.equal(g.run('S.cratesRun'),0);assert.equal(g.run('crateAd'),null);});
test('Basic free supply respects existing modal and cooldown gates',()=>{const g=make(29,new Map(),'basic');g.run('openCrate()');assert.equal(g.run('S.gold'),0);g.run('S.crateCooldownMs=0;$("overlay").classList.add("show");openCrate()');assert.equal(g.run('S.gold'),0);});
test('Basic old simulated eligibility settles only ordinary reward',()=>{const g=make(29,new Map(),'basic');g.run('S.runSouls=9;wall=true;doPrestige();S.prestigeOffer.adRewarded=true;showPrestigeOffer();requestPrestigeAd();applyPrestige(2)');assert.equal(g.run('S.souls'),0);assert(!g.run('$("modalBox").innerHTML.includes("广告")'));g.run('applyPrestige(1)');assert.equal(g.run('S.souls'),9);assert.equal(g.run('S.prestiges'),1);});
test('Basic malformed save is never silently overwritten',()=>{const g=make(29,new Map(),'basic');g.storage.set('neonHunter','{');g.run('load();save();doReset()');assert.equal(g.storage.get('neonHunter'),'{');assert.equal(g.run('saveBlocked'),true);});
test('Basic supply cooldown remains real time at normal 2x',()=>{const g=make(29,new Map(),'basic');g.run('paused=false;S.bestEver=2;S.speed2=true;advanceCrateClock(.1)');assert.equal(g.run('S.crateCooldownMs'),59900);});
test('Basic English reforge and supply panels have no untranslated fragments',()=>{const g=make(29,new Map(),'basic','en');g.run('S.runSouls=9;wall=true;doPrestige();renderPanels()');assert(!/[\u3400-\u9fff]/.test(g.run('$("modalBox").innerHTML')));assert.equal(g.run('window.NeonI18n.missing.size'),0);});
console.log(`${passed}/${passed} release checks passed`);
