const {make}=require('./harness.cjs'),assert=require('assert'),fs=require('fs');const results=[];
const test=(name,fn)=>{try{const g=make();fn(g);results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}};
const equal=(g,expr,want)=>assert.deepStrictEqual(g.json(expr),want);
const boss=(g,n)=>g.run(`S.stage=${n};S.floor=100;S.mobIdx=5;spawnMob();onKill()`);
for(let n=1;n<=5;n++){
 test(`阶段${n}基础属性与读档`,g=>{g.run(`S.stage=${n};save();load()`);equal(g,'[S.stage,calcStats().atk,calcStats().hp]',[n,[8,12,16,24,32][n-1],[100,150,200,300,400][n-1]]);});
 test(`阶段${n}普通重塑保留阶段树碎片`,g=>{g.run(`S.stage=${n};S.floor=20;S.bestEver=30;S.souls=5;S.runSouls=7;S.tree.dmg=3;wall=true;doPrestige();applyPrestige(1)`);equal(g,'[S.stage,S.floor,S.tree.dmg,S.souls,S.bestEver]',[n,1,3,12,30]);});
}
for(let n=1;n<=4;n++){
 test(`${n}→${n+1}百层优先且不发重塑技能`,g=>{boss(g,n);equal(g,'[S.floor,S.stageUpgrade.status,S.prestigeOffer,S.pendingOffer||null,paused]',[100,'clear',null,null,true]);assert(!g.run('$("stagePanel").innerHTML.includes("已通关")'));g.advance(1399);assert(!g.run('$("stagePanel").innerHTML.includes("已通关")'));g.advance(2);assert(g.run('$("stagePanel").innerHTML.includes("已通关")'));});
 test(`${n}→${n+1}资源全清、重复提交与日志保留`,g=>{g.run('S.gold=987;S.souls=234;S.runSouls=78;S.tree={dmg:5,gold:3,soul:8};S.atkLv=25;S.hpLv=17;S.skills=["nano"];S.equip.weapon={slot:"weapon",q:4};S.inv=[{slot:"armor",q:3}];S.prestiges=9;S.cratesRun=22;S.pity=9;S.sfxOn=false;S.speed2=true');boss(g,n);g.advance(1401);g.run('commitStageUpgrade();commitStageUpgrade()');equal(g,'[S.stage,S.floor,S.gold,S.souls,S.runSouls,S.atkLv,S.hpLv,S.prestiges,S.bestEver,S.pity,S.cratesRun]',[n+1,1,0,0,0,0,0,0,0,0,0]);equal(g,'[S.tree,S.inv,S.skills,S.equip,S.sfxOn,S.speed2,effSpeed()]',[{dmg:0,gold:0,soul:0},[],[],{weapon:null,implant:null,armor:null,chip:null},false,true,1]);equal(g,'[S.stageUpgrade.status,S.stageHistory.length,curSession.events.filter(e=>e.type==="stage_upgrade").length]',['playing',1,1]);g.advance(10000);equal(g,'[S.stage,S.floor,paused]',[n+1,1,true]);});
}
test('升阶写失败不清资源且可重试',g=>{boss(g,1);g.run('S.gold=777;var realWrite=localStorage.setItem;localStorage.setItem=()=>{throw Error("quota")};commitStageUpgrade()');equal(g,'[S.stage,S.gold,S.stageUpgrade.status]',[1,777,'clear']);g.run('localStorage.setItem=realWrite;commitStageUpgrade()');equal(g,'[S.stage,S.gold,S.stageUpgrade.status]',[2,0,'playing']);});
test('未播放不可完成或提前进入',g=>{boss(g,1);g.run('commitStageUpgrade();enterNextStage();completeStageAnimation();doReset();openCrate();doPrestige();$("btnAtk").onclick()');equal(g,'[S.stage,S.gold,S.stageUpgrade.status,paused]',[2,0,'playing',true]);});
test('播放中刷新从保存点继续且不重复升阶',g=>{boss(g,2);g.run('commitStageUpgrade();stageClock.elapsed=3.25;persistStagePlayback();load();openingRunIn()');equal(g,'[S.stage,S.stageUpgrade.status,stageClock.elapsed,S.stageHistory.length]',[3,'playing',3.25,1]);});
test('完成页刷新不重播，入场提交一次',g=>{boss(g,3);g.run('commitStageUpgrade();stageClock.elapsed=8;completeStageAnimation();load();openingRunIn()');equal(g,'[S.stage,S.stageUpgrade.status]',[4,'complete']);g.run('enterNextStage();enterNextStage()');g.advance(5000);equal(g,'[S.stage,S.floor,S.stageUpgrade,paused]',[4,1,null,false]);});
test('完成页与入场各自写失败可恢复',g=>{boss(g,1);g.run('commitStageUpgrade();stageClock.elapsed=8;var wr=localStorage.setItem;localStorage.setItem=()=>{throw Error("quota")};completeStageAnimation()');equal(g,'S.stageUpgrade.status','playing');g.run('localStorage.setItem=wr;completeStageAnimation();localStorage.setItem=()=>{throw Error("quota")};enterNextStage()');equal(g,'S.stageUpgrade.status','complete');g.run('localStorage.setItem=wr;enterNextStage()');equal(g,'S.stageUpgrade',null);});
test('旧高层档不清资源且先迁移预览，仅升一阶',g=>{g.run('var old={...freshState(),floor:301,gold:12345,souls:88};delete old.stage;delete old.stageSchema;localStorage.setItem("neonHunter",JSON.stringify(old));load();openingRunIn()');equal(g,'[S.stage,S.gold,S.souls,S.stageUpgrade.status,S.stageUpgrade.legacy]',[1,12345,88,'clear',true]);assert(g.storage.get('neonHunter.preStages'));g.run('commitStageUpgrade()');equal(g,'S.stage',2);});
test('旧百层待选技能不丢，选完再迁移预览',g=>{g.run('var old={...freshState(),floor:101,gold:888,pendingOffer:{pool:"p10",picks:["nano","fire","fatal"],floor:100}};delete old.stageSchema;delete old.stage;localStorage.setItem("neonHunter",JSON.stringify(old));load();openingRunIn()');g.advance(5000);equal(g,'[skillOfferOpen,S.stageUpgrade,S.gold]',[true,null,888]);g.run('pickSkill(curOffer[0])');equal(g,'[S.stageUpgrade.status,S.skills.length]',['clear',1]);});
test('旧百层重塑先结算再显示升阶清空预览',g=>{g.run('S.floor=101;S.runSouls=12;S.gold=99;S.prestigeOffer=makePrestigeOffer("milestone",100,"preview");var old={...S};delete old.stageSchema;delete old.stage;localStorage.setItem("neonHunter",JSON.stringify(old));load();openingRunIn();applyPrestige(1)');equal(g,'[S.stage,S.souls,S.stageUpgrade.status,S.stageUpgrade.legacy]',[1,12,'clear',true]);});
for(const raw of ['{',JSON.stringify({floor:1,stageSchema:900}),JSON.stringify({floor:1,stage:6}),JSON.stringify({floor:1,stage:2,stageUpgrade:{status:'playing',from:1,to:3,id:'x',elapsed:0}})]){
 test(`异常存档保护 ${raw}`,g=>{g.storage.set('neonHunter',raw);g.run('load();save()');assert.equal(g.storage.get('neonHunter'),raw);equal(g,'saveBlocked',true);});
}
for(const f of [100,200])test(`第五阶段${f}正常重塑选择并继续`,g=>{g.run(`S.stage=5;S.floor=${f};S.mobIdx=5;spawnMob();onKill()`);g.advance(1401);equal(g,'[S.floor,S.stageUpgrade,S.prestigeOffer.floor]',[f+1,null,f]);g.run('continueMilestone();pickSkill(curOffer[0])');g.advance(5000);equal(g,'[S.stage,S.floor,paused]',[5,f+1,false]);});
test('无尽掉落档位与本轮层数',g=>{g.run('S.stage=5');equal(g,'[dropBand(149),dropBand(150),dropBand(249),dropBand(250)]',[[3,5],[4,6],[4,6],[5,7]]);});
test('完成四次改装从第五阶段第一层无尽',g=>{for(let n=1;n<=4;n++){boss(g,n);g.advance(1401);g.run('commitStageUpgrade();stageClock.elapsed=8;completeStageAnimation();enterNextStage()');g.advance(5000);}equal(g,'[S.stage,S.floor,S.stageHistory.length,S.stageUpgrade]',[5,1,4,null]);});
test('旧广告及技能回调不能干扰改装',g=>{boss(g,1);g.run('commitStageUpgrade();finishPrestigeAd(1,"completed");offerSkills("p10");startFloorTransit();checkWall(9999)');equal(g,'[S.stage,S.floor,S.gold,skillOfferOpen,transit,paused]',[2,1,0,false,false,true]);});
function fakeRenderer(g){g.run(`matchMedia=()=>({matches:false});var p=UPGRADE_PACKS[S.stageUpgrade.from];window[p.api]={render:()=>({phase:'测试绘制'})};boot.assets=Object.values(p[UPGRADE_TIER]).map(url=>({url,state:'ready',image:{}}));$('upgradeCanvas').getContext=()=>({});$('upgradeProgress').setAttribute=()=>{};`);}
test('前台播放完整8秒，不受2倍速影响',g=>{boss(g,1);g.run('commitStageUpgrade();S.speed2=true;S.bestEver=100');fakeRenderer(g);g.run('playStageFrame(0);for(let i=1;i<=79;i++)playStageFrame(i*100)');equal(g,'[S.stageUpgrade.status,effSpeed()]',['playing',2]);assert(g.run('stageClock.elapsed<8'));g.run('playStageFrame(8000);playStageFrame(8100)');equal(g,'S.stageUpgrade.status','complete');});
test('后台与长时间挂起不折算观看时长',g=>{boss(g,1);g.run('commitStageUpgrade()');fakeRenderer(g);g.run('playStageFrame(0);playStageFrame(100);document.hidden=true;playStageFrame(900000)');assert(g.run('Math.abs(stageClock.elapsed-.1)<1e-9'));g.run('document.hidden=false;playStageFrame(900100);playStageFrame(901100)');assert(g.run('Math.abs(stageClock.elapsed-.2)<1e-9'));equal(g,'S.stageUpgrade.status','playing');});
test('演出素材缺失不计时、不开放继续',g=>{boss(g,1);g.run('commitStageUpgrade();playStageFrame(1000000)');equal(g,'[stageClock.elapsed,S.stageUpgrade.status]',[0,'playing']);assert(g.run('$("stageActions").innerHTML.includes("重试加载")'));});
test('绘制异常保留未观看时间且可重试',g=>{boss(g,1);g.run('commitStageUpgrade()');fakeRenderer(g);g.run('window[p.api].render=()=>{throw Error("GPU")};playStageFrame(0);playStageFrame(100)');equal(g,'[stageClock.elapsed,S.stageUpgrade.status]',[0,'playing']);assert(g.run('$("stageActions").innerHTML.includes("重试演出")'));});
test('第四第五阶段射击不再被330ms定时器截断',g=>{for(const [n,ms] of [[4,400],[5,560]]){g.run(`S.stage=${n};__realLunge("player")`);g.advance(ms-1);assert(g.run('$("playerSpr").classList.contains("atk")'));g.advance(12);assert(!g.run('$("playerSpr").classList.contains("atk")'));}});
fs.writeFileSync(__dirname+'/stage-results.json',JSON.stringify(results,null,2));console.log(`${results.filter(x=>x.status==='PASS').length}/${results.length} PASS`);for(const r of results.filter(x=>x.status==='FAIL'))console.log(r.name,r.error);if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
