const {make}=require('./core-tests.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync(__dirname+'/site/index.html','utf8');
const actualAnimationFunctions=html.match(/function enemyAnim\(cls,ms\)\{[\s\S]*?(?=function onKill\()/)[0];
const results=[];
function test(name,fn){const g=make();try{g.run(actualAnimationFunctions);fn(g);results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function spider(g){g.run('S.mobIdx=1;mobKind="spider";spawnMob();');}
test('三等分边界都选择正确类型',g=>{for(const [x,type] of [[0,'trooper'],[1/3-1e-8,'trooper'],[1/3,'hound'],[2/3-1e-8,'hound'],[2/3,'spider'],[.99999999,'spider']]){assert.equal(g.run(`Math.random=()=>${x};pickNormalMobKind()`),type);}});
test('9000 次有种子随机抽取三种类型均约三分之一',g=>{const counts=g.json('(()=>{const c={trooper:0,hound:0,spider:0};for(let i=0;i<9000;i++)c[pickNormalMobKind()]++;return c})()');for(const v of Object.values(counts))assert(Math.abs(v-3000)<200,JSON.stringify(counts));results.push({name:'随机取样分布',pass:true,counts});});
for(const [x,kind] of [[.1,'trooper'],[.5,'hound'],[.9,'spider']])test(kind+' 入场与就位使用同一类型，只抽取一次',g=>{g.run(`var rolls=0;Math.random=()=>{rolls++;return ${x}};enemyRunIn()`);assert.equal(g.run('mobKind'),kind);assert(g.run('$("enemySpr").classList.contains("run")'));g.advance(410);assert.equal(g.run('mobKind'),kind);assert.equal(g.run('rolls'),1);assert(!g.run('$("enemySpr").classList.contains("run")'));assert.equal(g.run('$("enemy").classList.contains("spider")'),kind==='spider');assert.equal(g.run('$("enemy").classList.contains("hound")'),kind==='hound');});
for(const floor of [1,10,100])test('f'+floor+' Boss 不参与普通池且清除蜘蛛外观',g=>{spider(g);g.run(`S.floor=${floor};S.mobIdx=5;Math.random=()=>{throw Error('Boss should not roll')};enemyRunIn()`);assert.equal(g.run('mobKind'),'trooper');assert(!g.run('$("enemy").classList.contains("spider")'));assert(g.run('$("enemy").classList.contains("boss")'));});
test('三种普通敌人血攻盾和信用点完全相同',g=>{const vals=g.json('NORMAL_MOB_KINDS.map(k=>{S.floor=37;S.mobIdx=1;mobKind=k;spawnMob();return [cur.max,cur.atk,cur.shield,calcGold(S.floor,false)]})');assert.deepEqual(vals[0],vals[1]);assert.deepEqual(vals[1],vals[2]);});
test('蜘蛛射击完整660ms且不被hurt/重复shoot打断',g=>{spider(g);g.run('enemyAnim("shoot",333)');g.advance(200);g.run('enemyAnim("hurt",200);enemyAnim("shoot",333)');g.advance(459);assert(g.run('$("enemySpr").classList.contains("shoot")'));assert(!g.run('$("enemySpr").classList.contains("hurt")'));g.advance(1);assert(!g.run('$("enemySpr").classList.contains("shoot")'));});
test('蜘蛛动画不额外结算伤害',g=>{spider(g);const hp=g.run('player.hp');g.run('enemyAnim("shoot",333)');g.advance(660);assert.equal(g.run('player.hp'),hp);});
test('死亡立即打断射击，旧回调不移除死亡态',g=>{spider(g);g.run('enemyAnim("shoot",333)');g.advance(100);g.run('enemyDie()');g.advance(700);assert(g.run('$("enemySpr").classList.contains("die")'));assert(!g.run('$("enemySpr").classList.contains("shoot")'));});
for(const speed of [false,true])test('蜘蛛完整死亡→淡出→下一怪 '+(speed?2:1)+'×',g=>{spider(g);g.run(`S.bestEver=10;S.speed2=${speed};onKill();var entries=0;enemyRunIn=()=>entries++`);const rate=speed?2:1;g.advance(1410/rate-1);assert.notEqual(g.run('$("enemy").style.opacity'),'0');g.advance(1);assert.equal(g.run('$("enemy").style.opacity'),'0');g.advance(350/rate-1);assert.equal(g.run('entries'),0);g.advance(1);assert.equal(g.run('entries'),1);});
test('死亡途中1→2倍速按剩余时间推进',g=>{spider(g);g.run('S.bestEver=10;onKill()');g.advance(500);g.run('S.speed2=true;syncPresentationSpeed()');g.advance(454);assert.notEqual(g.run('$("enemy").style.opacity'),'0');g.advance(1);assert.equal(g.run('$("enemy").style.opacity'),'0');});
test('死亡途中复位取消旧刷新回调',g=>{spider(g);g.run('onKill()');g.advance(400);g.run('beginPresentationRun();var entries=0;enemyRunIn=()=>entries++');g.advance(5000);assert.equal(g.run('entries'),0);});
test('第五只蜘蛛死亡后 Boss 正确换肤',g=>{spider(g);g.run('S.mobIdx=4;onKill()');g.advance(2170);assert(g.run('isBoss()&&mobKind==="trooper"&&$("enemy").classList.contains("boss")'));assert(!g.run('$("enemy").classList.contains("spider")'));});
test('原安保兵与犬换怪等待仍为1650ms',g=>{g.run('mobKind="hound";S.mobIdx=1;spawnMob();onKill();var entries=0;enemyRunIn=()=>entries++');g.advance(1649);assert.equal(g.run('entries'),0);g.advance(1);assert.equal(g.run('entries'),1);});
const report={environment:'Node VM actual game functions + DOM stubs / virtual clock',passed:results.filter(x=>x.pass).length,total:results.length,results};fs.writeFileSync(__dirname+'/spider-results.json',JSON.stringify(report,null,2));console.log('Spider '+report.passed+'/'+report.total);for(const r of results.filter(x=>!x.pass))console.log(r);process.exitCode=results.every(x=>x.pass)?0:1;
